### PR TITLE
add: input + image components

### PR DESCRIPTION
**Pull request by nayyyhaa**
**Made the following changes:**
- Input component with: Input variants & form validations.
- Image Component: Responsive, round, and curved images.

**current folder structure:**
```
inNotion-UI-library
               |______assets/ imgs
               |______styles
                            |__components-styles
                                          |______alert.css
                                          |______avatar.css
                                          |______badge.css
                                          |______button.css
                                          |______card.css
                                          |______image.css
                                          |______input.css
                            |__utils
                                    |______container/flex/grid/utilities/size/gutter/lists/font.css
                            |__main.css
               |______app.js
               |______index.html
               |______in-notion.css
               |______README.md
```

### CODE REVIEW

**Review by foolhardy21 — APPROVED** [review]
LGTM 👍🏾. nice that you replaced div with p tags. The use of classes also looks good.

**Review by partha8 — APPROVED** [review]
LGTM! Great work

**Review by shahbazibnafzal — APPROVED** [review]
nicely done.

**Comment by nayyyhaa** [comment]
> LGTM 👍🏾. nice that you replaced div with p tags. The use of classes also looks good.

Yes, after reviewing I noticed that. :D divs are now bugging me. Haha!

**Comment by nayyyhaa** [comment]
Thanks @foolhardy21 , @partha8  & @shahbaz4595 for reviewing! Merging the changes.

**Comment by vrx29** [comment]
looks good

**Pull request merged**
