### PR TITLE
add: card component

### PR DESCRIPTION
**Pull request by nayyyhaa**
**Made the following changes:**
- Card component with: badge, text overlay.
- Cards variant: horizontal & vertical, dismiss, text-only cards

**current folder structure:**
```
inNotion-UI-library
               |______assets/ imgs
               |______styles
                            |__components-styles
                                          |______alert.css
                                          |______avatar.css
                                          |______badge.css
                                          |______button.css
                                          |______card.css
                            |__utils
                                    |______container/flex/grid/utilities/size/gutter/lists/font.css
                            |__main.css
               |______app.js
               |______index.html
               |______in-notion.css
               |______README.md
```

### CODE REVIEW

**Comment by Dev-AkshatGupta** [comment]
Amazing Neha everything seems good . And you UI is dope :)

**Comment by vrinda-mahajan** [comment]
Everything looks great!

**Comment by nayyyhaa** [comment]
> Amazing Neha everything seems good . And you UI is dope :)

Hey, thank you so much @Dev-AkshatGupta ! :D

**Review by Maianki — APPROVED** [review]
Looks good to me. You can merge it.

**Comment by nayyyhaa** [comment]
> Everything looks great!

Thanks @vrinda-mahajan :D

**Comment by nayyyhaa** [comment]
> Looks good to me. You can merge it.

Thanks @m

> Looks good to me. You can merge it.

Thanks @Maianki ! Merging the changes then.

**Pull request merged**
