### PR TITLE
Badge button branch

### PR DESCRIPTION
**Pull request by nayyyhaa**
**Made the following changes:**
- Badge component: on avatar, icon, button & texts
- Button component: primary, colored, disabled, floating action

**current folder structure:**
```
inNotion-UI-library
               |______assets/ imgs
               |______styles
                            |__components-styles
                                          |______alert.css
                                          |______avatar.css
                                          |______badge.css
                                          |______button.css
                            |__utils
                                    |______container/flex/grid/utilities/width/gutter/lists/font.css
                            |__main.css
               |______app.js
               |______index.html
               |______in-notion.css
               |______README.md
```

### CODE REVIEW

**Comment by vrinda-mahajan** [comment]
The close button in the alert has an elliptical background try to give it a circular background, other than this everything looks great.

**Comment by nayyyhaa** [comment]
> The close button in the alert has an elliptical background try to give it a circular background, other than this everything looks great.

Thanks @vrinda-mahajan ! I've made the changes as mentioned. :D

**Comment by foolhardy21** [comment]
The UI is amazing. the code also looks good to me. A small observation. hovering on primary filled button makes it look like the disabled primary filled button thus giving the same idea to the user.

**Comment by nayyyhaa** [comment]
> The UI is amazing. the code also looks good to me. A small observation. hovering on primary filled button makes it look like the disabled primary filled button thus giving the same idea to the user.

Great observations! will make these changes.

**Pull request merged**
